import type { Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: 1,
    name: "Revenue Optimization & Reporting",
    role: "Data Analyst",
    skills: [
      "SQL",
      "Python",
      "Excel",
      "Tableau",
      "Power BI",
      "Statistics",
      "Data Analysis",
    ],
    client: "Hampton Inn & Suites by Hilton",
    points: [
      "Conducted data analysis to reduce billing discrepancies by 25%, improving guest satisfaction across the property.",
      "Delivered on-time revenue reports to executives, driving a 10% increase in efficiency through valuable insights and strategic improvements.",
      "Forecasted and achieved a 90% reservation conversion rate through effective upselling and personalized interactions, increasing room revenue.",
      "Analyzed seasonal customer footfall by age groups to determine optimal food stock levels for pantry, reducing food wastage by 30% and increasing time efficiency by 40%.",
    ],
    link: "",
  },
  {
    id: 2,
    name: "Aviation Services Data Marts",
    role: "Data Engineer",
    skills: [
      "Azure Synapse",
      "SSMS",
      "SQL",
      "ETL",
      "Data Marts",
      "Access Management",
    ],
    client: "Tata Technologies — Singapore Client",
    points: [
      "Extracted, transformed and loaded incremental and full load data from OLTP databases to data marts using Azure Synapse, reducing overall costs by 20%.",
      "Expedited the development and access management of two data marts by 20%, using SSMS to enable quick, critical insights access for 2,500 users.",
      "Provided on-call operational support for critical job failures, reducing mean time to recovery and maintaining high availability of data pipelines.",
      "Collaborated with US-based clients and stakeholders to deliver robust data validation strategies and ensure adherence to secure data practices and compliance requirements.",
    ],
    link: "",
  },
  {
    id: 3,
    name: "Cloud Migration Pipelines",
    role: "Data Engineer",
    skills: [
      "Databricks",
      "Azure Data Factory",
      "SQL",
      "Unity Catalog",
      "Python",
      "Spark",
    ],
    client: "Tata Technologies — German Automobile Client",
    points: [
      "Designed, developed, and maintained secure data pipelines on Databricks (SQL notebooks, Unity Catalog) and Azure Data Factory.",
      "Orchestrated ingestion, transformation, and enrichment of multi-terabyte datasets for a major German automobile manufacturer.",
      "Ensured data integrity and security across cloud-based pipeline infrastructure during large-scale migration.",
    ],
    link: "",
  },
  {
    id: 4,
    name: "Business Rule Development & Validation",
    role: "Data Engineer",
    skills: [
      "Databricks",
      "SQL",
      "Data Validation",
      "Python",
      "Business Analysis",
      "Stakeholder Management",
    ],
    client: "Tata Technologies — US Medical Technology Client",
    points: [
      "Worked closely with business analysts, SMEs, and developers to design and document over 50 business transformation rules aligned to domain requirements.",
      "Extracted and validated data, executing ad-hoc investigations through Databricks SQL workbooks to streamline issue resolution.",
      "Presented data findings and engaged with stakeholders to drive alignment on data quality and transformation outcomes.",
    ],
    link: "",
  },
];
